[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
solc_version = "0.8.30"
evm_version = "cancun"
optimizer = true
optimizer_runs = 10_000
via_ir = true
bytecode_hash = "none"
cbor_metadata = false
fs_permissions = [
  { access = "read", path = "./deployments" },
  { access = "read-write", path = "./proof" }
]

[profile.ci]
fuzz = { runs = 10_000 }
invariant = { runs = 1_000, depth = 100, fail_on_revert = false }

[profile.coverage]
via_ir = false
optimizer = false

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "long"
quote_style = "double"
number_underscore = "thousands"
multiline_func_header = "params_first"

[rpc_endpoints]
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
base = "${BASE_MAINNET_RPC_URL}"

[etherscan]
base_sepolia = { key = "${BASESCAN_API_KEY}", chain = 84532, url = "https://api-sepolia.basescan.org/api" }
base = { key = "${BASESCAN_API_KEY}", chain = 8453, url = "https://api.basescan.org/api" }
